export const PRICES_NFL = {
    "New-York-Giants": {
      "Minnesota-Vikings-at-New-York-Giants": 111,
      "Dallas-Cowboys-at-New-York-Giants": 115,
      "Cincinnati-Bengals-at-New-York-Giants": 77,
      "Philadelphia-Eagles-at-New-York-Giants": 125,
      "Washington-Commanders-at-New-York-Giants": 64,
      "Tampa-Bay-Buccaneers-at-New-York-Giants": 49,
      "New-Orleans-Saints-at-New-York-Giants": 44,
      "Baltimore-Ravens-at-New-York-Giants": 55,
      "Indianapolis-Colts-at-New-York-Giants": 31,
    },
    "Detroit-Lions": {
      "Los-Angeles-Rams-at-Detroit-Lions": 191,
      "Tampa-Bay-Buccaneers-at-Detroit-Lions": 167,
      "Seattle-Seahawks-at-Detroit-Lions": 194,
      "Tennessee-Titans-at-Detroit-Lions": 197,
      "Jacksonville-Jaguars-at-Detroit-Lions": 190,
      "Chicago-Bears-at-Detroit-Lions": 271,
      "Green-Bay-Packers-at-Detroit-Lions": 244,
      "Buffalo-Bills-at-Detroit-Lions": 243,
      "Minnesota-Vikings-at-Detroit-Lions": 145,
    },
    "Pittsburgh-Steelers": {
      "Los-Angeles-Chargers-at-Pittsburgh-Steelers": 175,
      "Dallas-Cowboys-at-Pittsburgh-Steelers": 316,
      "New-York-Jets-at-Pittsburgh-Steelers": 113,
      "New-York-Giants-at-Pittsburgh-Steelers": 81,
      "Baltimore-Ravens-at-Pittsburgh-Steelers": 164,
      "Cleveland-Browns-at-Pittsburgh-Steelers": 89,
      "Kansas-City-Chiefs-at-Pittsburgh-Steelers": 122,
      "Cincinnati-Bengals-at-Pittsburgh-Steelers": 62,
    },
    "Cleveland-Browns": {
      "Dallas-Cowboys-at-Cleveland-Browns": 172,
      "New-York-Giants-at-Cleveland-Browns": 65,
      "Cincinnati-Bengals-at-Cleveland-Browns": 85,
      "Baltimore-Ravens-at-Cleveland-Browns": 51,
      "Los-Angeles-Chargers-at-Cleveland-Browns": 40,
      "Pittsburgh-Steelers-at-Cleveland-Browns": 82,
      "Kansas-City-Chiefs-at-Cleveland-Browns": 91,
      "Miami-Dolphins-at-Cleveland-Browns": 41,
    },
    "Washington-Commanders": {
      "New-York-Giants-at-Washington-Commanders": 115,
      "Cleveland-Browns-at-Washington-Commanders": 70,
      "Carolina-Panthers-at-Washington-Commanders": 54,
      "Chicago-Bears-at-Washington-Commanders": 128,
      "Pittsburgh-Steelers-at-Washington-Commanders": 197,
      "Dallas-Cowboys-at-Washington-Commanders": 157,
      "Tennessee-Titans-at-Washington-Commanders": 50,
      "Philadelphia-Eagles-at-Washington-Commanders": 131,
      "Atlanta-Falcons-at-Washington-Commanders": 50,
    },
    "Baltimore-Ravens": {
      "Las-Vegas-Raiders-at-Baltimore-Ravens": 135,
      "Buffalo-Bills-at-Baltimore-Ravens": 165,
      "Washington-Commanders-at-Baltimore-Ravens": 152,
      "Denver-Broncos-at-Baltimore-Ravens": 99,
      "Cincinnati-Bengals-at-Baltimore-Ravens": 102,
      "Philadelphia-Eagles-at-Baltimore-Ravens": 217,
      "Pittsburgh-Steelers-at-Baltimore-Ravens": 140,
      "Cleveland-Browns-at-Baltimore-Ravens": 72,
    },
    "Philadelphia-Eagles": {
      "Atlanta-Falcons-at-Philadelphia-Eagles": 201,
      "Cleveland-Browns-at-Philadelphia-Eagles": 217,
      "Jacksonville-Jaguars-at-Philadelphia-Eagles": 161,
      "Washington-Commanders-at-Philadelphia-Eagles": 138,
      "Carolina-Panthers-at-Philadelphia-Eagles": 145,
      "Pittsburgh-Steelers-at-Philadelphia-Eagles": 189,
      "Dallas-Cowboys-at-Philadelphia-Eagles": 198,
      "New-York-Giants-at-Philadelphia-Eagles": 111,
    },
    "Miami-Dolphins": {
      "Jacksonville-Jaguars-at-Miami-Dolphins": 91,
      "Buffalo-Bills-at-Miami-Dolphins": 149,
      "Tennessee-Titans-at-Miami-Dolphins": 73,
      "Arizona-Cardinals-at-Miami-Dolphins": 85,
      "Las-Vegas-Raiders-at-Miami-Dolphins": 112,
      "New-England-Patriots-at-Miami-Dolphins": 108,
      "New-York-Jets-at-Miami-Dolphins": 135,
      "San-Francisco-49ers-at-Miami-Dolphins": 180,
    },
  };

const numberOfKeys = Object.keys(PRICES_NFL).length;
console.log(numberOfKeys); // This will log the number of keys in the PRICES_NFL object